# Generated by Django 2.0.3 on 2018-03-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('designer', 'Designer')], default='', max_length=10),
        ),
    ]
