# Generated by Django 2.0.3 on 2018-03-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('designer', 'Designer')], default='', max_length=10),
        ),
    ]
